config/routes.rb
Dictionary::Application.routes.draw do
  resources :words do
  post 'search', :on => :collection
  end
  root to: "words#index"

  

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
    @letter=(params[:word])
  end
  

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  #def edit
  #end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render action: 'show', status: :created, location: @word }
      else
        format.html { render action: 'new' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
  def search
      @words= Word.find(:all, :conditions => ["word LIKE ?", "#{params[:key]}"])
  end 
  
  
  # process the name and the letter
  #end
  #def lettersearch
  
   #Word.where(["word like ?", "#{params[:id]}%"])
  #end
  #end
 
 

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
     @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word, :wordtype, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dictionary</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :wordtype %><br>
    <%= f.text_field :wordtype %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<html>

<p align="center">
<h1 align="center">Listing words</h1>
</p>

<br>

<h3>Enter word</h3>

<form action ="words/search" method="post">
<input name = "key" type="input" />
<input value="Send" type="submit"/>
</form>
<br>

<%= link_to ('A'), words_path(:word=>'A')%>
<%= link_to ('B'), words_path(:word=>'B')%>
<%= link_to ('C'), words_path(:word=>'C')%>
<%= link_to ('C'), words_path(:word=>'C')%>
<%= link_to ('D'), words_path(:word=>'D')%>
<%= link_to ('E'), words_path(:word=>'E')%>
<%= link_to ('F'), words_path(:word=>'F')%>
<%= link_to ('G'), words_path(:word=>'G')%>
<%= link_to ('H'), words_path(:word=>'H')%>
<%= link_to ('I'), words_path(:word=>'I')%>
<%= link_to ('J'), words_path(:word=>'J')%>
<%= link_to ('K'), words_path(:word=>'K')%>
<%= link_to ('L'), words_path(:word=>'L')%>
<%= link_to ('M'), words_path(:word=>'M')%>
<%= link_to ('N'), words_path(:word=>'N')%>
<%= link_to ('O'), words_path(:word=>'O')%>
<%= link_to ('P'), words_path(:word=>'P')%>
<%= link_to ('Q'), words_path(:word=>'Q')%>
<%= link_to ('R'), words_path(:word=>'R')%>
<%= link_to ('S'), words_path(:word=>'S')%>
<%= link_to ('T'), words_path(:word=>'T')%>
<%= link_to ('U'), words_path(:word=>'U')%>
<%= link_to ('V'), words_path(:word=>'V')%>
<%= link_to ('W'), words_path(:word=>'W')%>
<%= link_to ('X'), words_path(:word=>'X')%>
<%= link_to ('Y'), words_path(:word=>'Y')%>
<%= link_to ('Z'), words_path(:word=>'Z')%>

<br>
<table>
  <thead>
    
  </thead>

  <tbody>
    <% @words.each do |word| %>
    <% if word.word.chars.first==@letter%>
    
    
      <tr>
        <td><%= word.word %></td>
        <td><%= word.wordtype %></td>
        <td><%= word.description %></td>
        <td><%= link_to 'Show', word %></td>
        
      </tr>
	<% else if @letter == nil %>
      <tr>
        <td><%= word.word %></td>
        <td><%= word.wordtype %></td>
        <td><%= word.description %></td>
        <td><%= link_to 'Show', word %></td>
        
      </tr>
	<% end %>
    <% end %>
    <% end %>
    
  </tbody>
</table>




<br/>
</html>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/search.html.erb
<html>
<head>
<title>Search results
</title>
</head>
<body>
<h1>Search results</h1>
<table border="1">
<tr>
<td width="40%"><p align="center"><i><b>Word</b></i></td>
<td width="20%"><p align="center"><i><b>WordType</b></i></td>
</tr>
<%@words.each do|word|%>
<tr>
<td>
<a href="
<%=word.id%>
">
<%=word.word%>
</a>
</td>
<td><%= word.wordtype %></td>
</tr>
<% end %>
</table>
<p> <a href="/words"> Back</a> </body>
</html>

app/views/words/show.html.erb
<head>
<script>
    function jsonFlickrApi(rsp) {
    if (rsp.stat != "ok"){
    // If this executes, something broke!
    return;
    }
    //variable "s" is going to contain
    //all the markup that is generated by the loop below
     var s = "";
    //this loop runs through every item and creates HTML
    for (var i=0; i <2; i++) {
    photo = rsp.photos.photo[ i ];
    //notice that "t.jpg" is where you change the
    //size of the image
      t_url = "http://farm" + photo.farm +
    ".static.flickr.com/" + photo.server + "/" +
    photo.id + "_" + photo.secret + "_" + "t.jpg";
    p_url = "http://www.flickr.com/photos/" +
    photo.owner + "/" + photo.id;
    s += '<a href="' + p_url + '">' + '<img alt="'+
    photo.title + '"src="' + t_url + '"/>' + '</a>';
    }
     
    document.writeln(s);
    //this tells the JavaScript to write
    //everything in variable "s" onto the page
    }
</script>
</head>
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Wordtype:</strong>
  <%= @word.wordtype %>
</p>

<p>
  <strong>Description:</strong>
  <%= @word.description %>
</p>
<!-- Start of Flickr Badge -->
<style type="text/css">
#flickr_badge_source_txt {padding:0; font: 11px Arial, Helvetica, Sans serif; color:#666666;}
#flickr_badge_icon {display:block !important; margin:0 !important; border: 1px solid rgb(0, 0, 0) !important;}
#flickr_icon_td {padding:0 5px 0 0 !important;}
.flickr_badge_image {text-align:center !important;}
.flickr_badge_image img {border: 1px solid black !important;}
#flickr_www {display:block; padding:0 10px 0 10px !important; font: 11px Arial, Helvetica, Sans serif !important; color:#3993ff !important;}
#flickr_badge_uber_wrapper a:hover,
#flickr_badge_uber_wrapper a:link,
#flickr_badge_uber_wrapper a:active,
#flickr_badge_uber_wrapper a:visited {text-decoration:none !important; background:inherit !important;color:#3993ff;}
#flickr_badge_wrapper {background-color:#ffffff;border: solid 1px #000000}
#flickr_badge_source {padding:0 !important; font: 11px Arial, Helvetica, Sans serif !important; color:#666666 !important;}
</style>
<table id="flickr_badge_uber_wrapper" cellpadding="0" cellspacing="10" border="0"><tr><td><a href="http://www.flickr.com" id="flickr_www">www.<strong style="color:#3993ff">flick<span style="color:#ff1c92">r</span></strong>.com</a><table cellpadding="0" cellspacing="10" border="0" id="flickr_badge_wrapper">
<tr>
<script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=1&display=latest&size=s&layout=h&source=all"></script>
</tr>
</table>
</td></tr></table>
<!-- End of Flickr Badge -->




<%= link_to 'Back', words_path %>
<script type="text/javascript" language="javascript" src="http://api.flickr.com/services/rest/?format=json&method=flickr.photos.search&tags=dog&tag_mode=all&api_key=8b4620283439412db1b2593e6129a211"></script>